services:
  # --- AIR SERVER BACKEND SERVICES --- #
  air-server-auth:
    networks:
      - dfir_network
    build:
      context: ./apps/air-server-backend
      dockerfile: ./services/auth/Dockerfile
    env_file:
      - ./apps/air-server-backend/services/auth/.env
    command: pnpm --filter air-server-backend run start:dev auth
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - rabbitmq

  air-server-responder:
    networks:
      - dfir_network
    build:
      context: ./apps/air-server-backend
      dockerfile: ./services/responder/Dockerfile
    env_file:
      - ./apps/air-server-backend/services/responder/.env
    command: pnpm --filter air-server-backend run start:dev responder
    ports:
      - 3001:3001
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - rabbitmq
      - emqx_broker

  air-server-ingestion:
    networks:
      - dfir_network
    build:
      context: ./apps/air-server-backend
      dockerfile: ./services/ingestion/Dockerfile
    env_file:
      - ./apps/air-server-backend/services/ingestion/.env
    command: pnpm --filter air-server-backend run start:dev ingestion
    volumes:
      - .:/usr/src/app
    depends_on:
      - rabbitmq
      - emqx_broker

  air-server-sync:
    networks:
      - dfir_network
    build:
      context: ./apps/air-server-backend
      dockerfile: ./services/sync/Dockerfile
    env_file:
      - ./apps/air-server-backend/services/sync/.env
    command: pnpm --filter air-server-backend run start:dev sync
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - redis

  air-server-job-service:
    networks:
      - dfir_network
    build:
      context: ./apps/air-server-backend
      dockerfile: ./services/job-service/Dockerfile
    env_file:
      - ./apps/air-server-backend/services/job-service/.env
    command: pnpm --filter air-server-backend run start:dev job-service
    ports:
      - 3002:3002
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - rabbitmq
      - emqx_broker

  # --- AIR SERVER FRONTEND SERVICE --- #
  air-server-frontend:
    networks:
      - dfir_network
    build:
      context: ./apps/air-server-frontend
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    depends_on:
      - air-server-auth
      - air-server-responder
      - air-server-job-service

  # --- ADMIN BACKEND SERVICES --- #
  admin-backend:
    networks:
      - dfir_network
    build:
      context: ./apps/admin-backend
      dockerfile: ./Dockerfile
    env_file:
      - ./apps/admin-backend/.env
    command: pnpm --filter admin-backend run start:dev
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres

  # --- EXTERNAL SERVICES --- #
  postgres:
    image: postgres:17.5-alpine3.22
    container_name: postgres
    networks:
      - dfir_network
    environment:
      POSTGRES_USER: dfiruser
      POSTGRES_PASSWORD: dfirpassword
      POSTGRES_DB: dfir_master
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.1.2-alpine
    container_name: rabbitmq
    networks:
      - dfir_network
    environment:
      - RABBITMQ_DEFAULT_USER=dfiruser
      - RABBITMQ_DEFAULT_PASS=dfirpassword
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:8.0.2-alpine
    container_name: redis
    networks:
      - dfir_network
    ports:
      - 6379:6379

  emqx_broker:
    image: emqx/emqx-enterprise:5.8.7
    container_name: emqx_broker
    ports:
      - 1883:1883
      - 8081:8081
      - 8883:8883
      - 18083:18083
    volumes:
      - ./emqx/emqx.conf:/opt/emqx/etc/emqx.conf
      - ./emqx/data:/opt/emqx/data
    networks:
      - dfir_network
    depends_on:
      - air-server-auth
networks:
  dfir_network:
    driver: bridge

volumes:
  postgres_data:
