services:
  # --- AIR SERVER BACKEND SERVICES --- #
  air-server-auth:
    networks:
      - dfir_network
    build:
      context: ./apps/air-server-backend
      dockerfile: ./services/auth/Dockerfile
    env_file:
      - ./apps/air-server-backend/services/auth/.env
    command: pnpm --filter air-server-backend run start:dev auth
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:17.5-alpine3.22
    container_name: postgres
    networks:
      - dfir_network
    environment:
      POSTGRES_USER: dfiruser
      POSTGRES_PASSWORD: dfirpassword
      POSTGRES_DB: dfir_master
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4.1.2-alpine
    container_name: rabbitmq
    networks:
      - dfir_network
    environment:
      - RABBITMQ_DEFAULT_USER=dfiruser
      - RABBITMQ_DEFAULT_PASS=dfirpassword
    ports:
      - 5672:5672

  redis:
    image: redis:8.0.2-alpine
    container_name: redis
    networks:
      - dfir_network
    ports:
      - 6379:6379

  emqx:
    image: emqx/emqx:5.8.7
    container_name: emqx_broker
    ports:
      - 1883:1883
      - 8081:8081
      - 8883:8883
      - 18083:18083
    volumes:
      - ./emqx/emqx.conf:/opt/emqx/etc/emqx.conf
      - ./emqx/plugins/emqx_auth_http.conf:/opt/emqx/etc/plugins/emqx_auth_http.conf
    networks:
      - dfir_network
    depends_on:
      - air-server-auth
networks:
  dfir_network:
    driver: bridge

volumes:
  postgres_data: