export const MASTER_DB_CONNECTION = "MASTER_DB_CONNECTION";
export const REDIS_CLIENT = "REDIS_CLIENT";
export const TENANT_CONNECTION = "TENANT_CONNECTION";
export const MQTT_CLIENT = "MQTT_CLIENT";
